apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: node-red
  chart:
    spec:
      chart: ./node-red/chart
  values:
    controller:
      image:
        repository: docker.io/nodered/node-red:3.0.2
        tag: "v3.0.2"
      image:
        repository: quay.io/kiwigrid/k8s-sidecar:1.22.0
        tag: "v1.22.0"
      replicaCount: 2
