apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: node-red
  chart:
    spec:
      chart: ./charts/node-red
  values:
    replicaCount: 3
    controller:
      image:
        repository: docker.io/nodered/node-red:3.0.2
        tag: "v3.0.2"
